version: 2.1

jobs:
  build:
    parameters:
      resource:
        type: string
    resource_class: << parameters.resource >>
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: lscpu

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              resource: ["medium", "large"]