version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && sudo -u joe -s
  gas2:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && sudo -u joe -s
  gas3:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && sudo -u joe -s
  gas4:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: sudo adduser --disabled-password --gecos "" joe && sudo usermod -aG sudo joe && sudo -u joe -s

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - gas1
      - gas2
      - gas3
      - gas4